// Always-on server: runs the Engine 24/7, owns the multi-timeframe SeriesStore,
// persists to SQLite, and exposes the stream to thin browser clients.
//
//   GET  /api/series?tf=&limit=   → history snapshot for one timeframe
//   GET  /api/stream?tf=          → SSE: live bar + header status (+ reset events)
//   POST /api/control/*           → token-gated mutations (reset/nudge/mode/…)
//   GET  /*                       → built client from dist/
//
// Viewing is open; every mutation requires the bearer token (see README).

import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { randomBytes, timingSafeEqual } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve, normalize } from 'node:path';

import { Engine, type EngineState } from '../shared/engine';
import { compact, isTf, TF_CAP, type TfSeconds } from '../shared/candles';
import { SPEED_NAMES, VOL_NAMES } from '../shared/regimes';
import { Db } from './db';
import { SeriesStore } from './seriesStore';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DIST = join(ROOT, 'dist');

const PORT = Number(process.env.PORT) || 8787;
const DB_PATH = process.env.DB_PATH || join(ROOT, 'data', 'market.db');
const FLUSH_MS = 2500;
const BROADCAST_MS = 100;
const HEARTBEAT_MS = 15000;

// ---- Token: from env, or auto-generated and printed once at boot ----
let CONTROL_TOKEN = process.env.CONTROL_TOKEN || '';
let tokenAutoGenerated = false;
if (!CONTROL_TOKEN) {
  CONTROL_TOKEN = randomBytes(24).toString('base64url');
  tokenAutoGenerated = true;
}

function tokenValid(provided: string | null | undefined): boolean {
  if (!provided) return false;
  const a = Buffer.from(provided);
  const b = Buffer.from(CONTROL_TOKEN);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

function bearer(req: IncomingMessage): string | null {
  const h = req.headers['authorization'];
  if (typeof h === 'string' && h.startsWith('Bearer ')) return h.slice(7).trim();
  const x = req.headers['x-control-token'];
  return typeof x === 'string' ? x.trim() : null;
}

// ---- Boot: DB → engine + store, restore or seed fresh ----
const db = new Db(DB_PATH);
const loaded = db.loadAll();

const engine = new Engine({
  onTick: (price, baseLast) => {
    store.onTick(price, baseLast.time);
    pendingTick = true;
  },
});
const store = new SeriesStore(engine, db);

function isValidEngineState(s: unknown): s is EngineState {
  if (!s || typeof s !== 'object') return false;
  const o = s as Record<string, unknown>;
  const num = (x: unknown) => typeof x === 'number' && Number.isFinite(x);
  const r = o.regime as Record<string, unknown> | undefined;
  return (
    num(o.price) &&
    num(o.simTimeMs) &&
    num(o.tickCount) &&
    num(o.startPrice) &&
    !!r &&
    typeof r === 'object' &&
    typeof r.name === 'string' &&
    num(r.minDelay) &&
    num(r.maxDelay) &&
    num(r.vol) &&
    num(r.speedTtl) &&
    num(r.volTtl)
  );
}

const restoredState = SeriesStore.parseEngineState(loaded);
if (isValidEngineState(restoredState) && (loaded.series.get(1)?.length ?? 0) > 0) {
  store.restore(loaded);
  engine.restore(restoredState, store.baseTail());
  console.log(`[boot] restored: price=${engine.price.toFixed(4)} base=${store.baseCount()} candles`);
} else {
  store.reset(); // seeds a fresh chart + persists it
  console.log('[boot] seeded a fresh chart');
}

// ---- SSE clients + broadcast ----
interface Client {
  res: ServerResponse;
  tf: TfSeconds;
}
const clients = new Set<Client>();
let pendingTick = false;

interface Status {
  price: number;
  startPrice: number;
  t: number;
  tps: number;
  tickCount: number;
  regime: string;
  vol: string;
  mode: string;
  multiplier: number;
  baseCount: number;
  running: boolean;
}
function status(): Status {
  return {
    price: engine.price,
    startPrice: engine.startPrice,
    t: engine.simTimeMs,
    tps: engine.ticksPerSecond(),
    tickCount: engine.tickCount,
    regime: engine.regimeName(),
    vol: engine.volName(),
    mode: engine.getMode(),
    multiplier: engine.getSpeedMultiplier(),
    baseCount: store.baseCount(),
    running: engine.isRunning(),
  };
}

function sseWrite(res: ServerResponse, event: string, data: unknown): void {
  res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
}

function tickPayload(tf: TfSeconds, st: Status): Record<string, unknown> {
  const bar = store.liveBar(tf);
  return { ...st, bar: bar ? compact(bar) : null };
}

function sendTick(client: Client, st: Status): void {
  sseWrite(client.res, 'tick', tickPayload(client.tf, st));
}

function broadcast(event: 'tick' | 'reset' | 'running'): void {
  const st = status();
  for (const c of clients) {
    if (event === 'tick') sendTick(c, st);
    else sseWrite(c.res, event, event === 'running' ? { running: st.running } : { t: st.t });
  }
}

setInterval(() => {
  if (!pendingTick) return;
  pendingTick = false;
  broadcast('tick');
}, BROADCAST_MS);

setInterval(() => {
  for (const c of clients) c.res.write(': ping\n\n');
}, HEARTBEAT_MS);

setInterval(() => {
  try {
    store.flush();
  } catch (e) {
    console.error('[flush] failed:', e);
  }
}, FLUSH_MS);

engine.start();

// ---- HTTP helpers ----
function setCors(res: ServerResponse): void {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Control-Token');
}

function sendJson(res: ServerResponse, code: number, body: unknown): void {
  const s = JSON.stringify(body);
  res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(s);
}

async function readJson(req: IncomingMessage): Promise<Record<string, unknown>> {
  const chunks: Buffer[] = [];
  let size = 0;
  for await (const chunk of req) {
    size += chunk.length;
    if (size > 1 << 16) throw new Error('body too large');
    chunks.push(chunk as Buffer);
  }
  if (chunks.length === 0) return {};
  try {
    return JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string, unknown>;
  } catch {
    return {};
  }
}

function parseTf(raw: string | null): TfSeconds {
  const n = Number(raw);
  return isTf(n) ? n : 1;
}

// ---- Route: GET /api/series ----
function handleSeries(_req: IncomingMessage, res: ServerResponse, url: URL): void {
  const tf = parseTf(url.searchParams.get('tf'));
  const limRaw = Number(url.searchParams.get('limit'));
  const limit = Number.isFinite(limRaw) && limRaw > 0 ? Math.min(limRaw, TF_CAP[tf]) : TF_CAP[tf];
  const bars = store.getSeries(tf, limit).map(compact);
  sendJson(res, 200, { tf, bars, ...status() });
}

// ---- Route: GET /api/stream (SSE) ----
function handleStream(req: IncomingMessage, res: ServerResponse, url: URL): void {
  const tf = parseTf(url.searchParams.get('tf'));
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
    'X-Accel-Buffering': 'no', // disable proxy buffering (nginx)
  });
  res.write('retry: 3000\n\n');
  const client: Client = { res, tf };
  clients.add(client);
  sendTick(client, status()); // immediate paint, don't wait for the next tick
  req.on('close', () => {
    clients.delete(client);
  });
}

// ---- Route: POST /api/control/* ----
async function handleControl(req: IncomingMessage, res: ServerResponse, action: string): Promise<void> {
  if (req.method !== 'POST') return sendJson(res, 405, { error: 'method not allowed' });
  if (!tokenValid(bearer(req))) return sendJson(res, 401, { error: 'invalid or missing token' });

  if (action === 'verify') return sendJson(res, 200, { ok: true });

  const body = await readJson(req);

  switch (action) {
    case 'reset': {
      store.reset();
      engine.start();
      broadcast('reset');
      pendingTick = true;
      return sendJson(res, 200, { ok: true });
    }
    case 'nudge': {
      const delta = Number(body.delta);
      if (!Number.isFinite(delta)) return sendJson(res, 400, { error: 'delta must be a number' });
      engine.nudge(delta);
      pendingTick = true;
      return sendJson(res, 200, { ok: true, price: engine.price });
    }
    case 'pause': {
      engine.pause();
      store.flush();
      broadcast('running');
      return sendJson(res, 200, { ok: true, running: false });
    }
    case 'resume': {
      engine.start();
      broadcast('running');
      return sendJson(res, 200, { ok: true, running: true });
    }
    case 'mode': {
      const mode = body.mode === 'manual' ? 'manual' : 'auto';
      engine.setMode(mode);
      if (mode === 'manual') {
        if (typeof body.speed === 'string' && SPEED_NAMES.includes(body.speed)) engine.setManualSpeed(body.speed);
        if (typeof body.vol === 'string' && VOL_NAMES.includes(body.vol)) engine.setManualVol(body.vol);
      }
      pendingTick = true;
      return sendJson(res, 200, { ok: true });
    }
    case 'regime': {
      if (typeof body.speed === 'string' && SPEED_NAMES.includes(body.speed)) engine.setManualSpeed(body.speed);
      if (typeof body.vol === 'string' && VOL_NAMES.includes(body.vol)) engine.setManualVol(body.vol);
      pendingTick = true;
      return sendJson(res, 200, { ok: true });
    }
    default:
      return sendJson(res, 404, { error: 'unknown control' });
  }
}

// ---- Static client (dist/) ----
const CONTENT_TYPE: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.json': 'application/json; charset=utf-8',
  '.ico': 'image/x-icon',
  '.png': 'image/png',
  '.woff2': 'font/woff2',
  '.map': 'application/json; charset=utf-8',
};

async function serveStatic(res: ServerResponse, pathname: string): Promise<void> {
  const rel = normalize(pathname === '/' ? '/index.html' : pathname).replace(/^(\.\.[/\\])+/, '');
  const filePath = join(DIST, rel);
  if (!filePath.startsWith(DIST)) {
    res.writeHead(403);
    res.end('forbidden');
    return;
  }
  try {
    const data = await readFile(filePath);
    const ext = filePath.slice(filePath.lastIndexOf('.'));
    res.writeHead(200, { 'Content-Type': CONTENT_TYPE[ext] || 'application/octet-stream' });
    res.end(data);
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end('Not found. Run `npm run build` to produce dist/, or use the Vite dev server (npm run dev).');
  }
}

// ---- Server ----
const server = createServer((req, res) => {
  setCors(res);
  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }
  const url = new URL(req.url || '/', 'http://localhost');
  const p = url.pathname;

  if (p === '/api/series') return void handleSeries(req, res, url);
  if (p === '/api/stream') return void handleStream(req, res, url);
  if (p.startsWith('/api/control/')) {
    handleControl(req, res, p.slice('/api/control/'.length)).catch((e) => {
      console.error('[control] error:', e);
      sendJson(res, 500, { error: 'internal error' });
    });
    return;
  }
  if (p === '/api/health') return void sendJson(res, 200, { ok: true, ...status() });
  if (req.method === 'GET') return void serveStatic(res, p);
  res.writeHead(404);
  res.end();
});

server.listen(PORT, () => {
  console.log(`\n  ENTROPY server → http://127.0.0.1:${PORT}`);
  console.log(`  db: ${DB_PATH}`);
  if (tokenAutoGenerated) {
    console.log('\n  ┌─ CONTROL TOKEN (auto-generated; set CONTROL_TOKEN to pin it) ─');
    console.log(`  │  ${CONTROL_TOKEN}`);
    console.log('  └────────────────────────────────────────────────────────────\n');
  } else {
    console.log('  control token: (from CONTROL_TOKEN env)\n');
  }
});

// ---- Graceful shutdown: final flush so the stream resumes seamlessly ----
let shuttingDown = false;
function shutdown(signal: string): void {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log(`\n[${signal}] flushing + closing…`);
  engine.pause();
  try {
    store.flush();
  } catch (e) {
    console.error('[shutdown] flush failed:', e);
  }
  try {
    db.close();
  } catch {
    /* ignore */
  }
  server.close(() => process.exit(0));
  setTimeout(() => process.exit(0), 2000).unref();
}
process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));
